### ISSUE TITLE
CalibrateJoystick

### ISSUE THREAD

**Issue by ep94** [YuriiSalimov/AxisJoystick#2]
Line 27 causes error: 'class Joystick' has no member named 'calibrate'
  joystic->calibrate(LOW_RANGE, HIGH_RANGE, RANGE_DIVITION);

**Comment by suoapvs** [comment]
I have no such errors. Try to update the library to the latest version.

**Comment by ep94** [comment]
Deleted axisjoystick from my library directory and reloaded it again (Ver. 2.1.0). Now its working, thanks for the suggestion.
