### ISSUE TITLE
documentation for calibration

### ISSUE THREAD

**Issue by thijstriemstra** [YuriiSalimov/AxisJoystick#3]
after testing the examples, it looks like the joystick I'm using needs to be calibrated because I see vrx=506 and vry=510 in neutral position.

After checking the CalibrateJoystick example, it's not clear how this calibrate actually works. Should these vrx and vry be 'calibrated'?

**Comment by suoapvs** [comment]
Calibration is the setting of the axis response range.
For example, for Arduino, the joystick axis (vrx or vry), when pressed in different directions, 
can return a value in the range [10, 980] (for different joysticks, these values ​​can be different, ideally [0, 1023]).

Then we can set the lower bound of the range to 100 (must by great than the minimum axis value), 
and the upper bound to 900 (must by less than the maximum axis value).
[0, 100] - the axis is pressed down,
[900, 1023] - the axis is pressed up,
(100, 900) - the axis is not pressed.
By default, this range is [100, 923].

For calibration, we can use 2 methods:

1) `calibrate (int low, int high)`
low - the lower bound of the values range,
high - the upper bound of the values range.
In the example above: low = 100, high = 900.

2) Or `calibrate(int adcMin, int adcMax, int deviation)`
adcMin - min value of the board ADC (for Arduino, 0);
adcMax - max value of the board ADC (for Arduino, 1023);
deviation - deviation from the value’s axis range (default, 100),
when the axis is considered pressed.
low = (adcMin + deviation)
high = (adcMax - deviation).
For Arduino: adcMin = 0, adcMax = 1023, deviation = 100 
=> low = 0 + 100 = 100, high = 1023 - 100 = 923.

**Comment by thijstriemstra** [comment]
**Test results**

Using:
```
platform = espressif32
board = esp32doit-devkit-v1
framework = arduino
```

Neutral position:

```
| SingleRead: NOT | MultipleRead: UP | Press: 0 | Up: 1 | Down: 0 | Right: 1 | Left: 0 | 
VRx: 1861 | VRy: 1840 | SW: 1 |
```

Down:

```
| SingleRead: NOT | MultipleRead: DOWN | Press: 0 | Up: 0 | Down: 1 | Right: 1 | Left: 0 | 
VRx: 1863 | VRy: 0 | SW: 1 |
```

Up:

```
| SingleRead: NOT | MultipleRead: UP | Press: 0 | Up: 1 | Down: 0 | Right: 1 | Left: 0 | 
VRx: 1863 | VRy: 4095 | SW: 1 |
```

Left:

```
| SingleRead: NOT | MultipleRead: UP | Press: 0 | Up: 1 | Down: 0 | Right: 0 | Left: 1 |
VRx: 0 | VRy: 1840 | SW: 1 |
```

Right:

```
| SingleRead: NOT | MultipleRead: UP | Press: 0 | Up: 1 | Down: 0 | Right: 1 | Left: 0 | 
VRx: 4095 | VRy: 1843 | SW: 1 |
```

So basically it only seems to detect UP and DOWN. Leaving it in neutral position reads UP, and LEFT and RIGHT are not detected.

I'm using:

```cpp
#define SW_PIN 27
#define VRX_PIN 26
#define VRY_PIN 25
#define ARDUINO_ADC_MIN 0
#define ARDUINO_ADC_MAX 1023
#define AXES_DEVIATION 100

joystic = new AxisJoystick(SW_PIN, VRX_PIN, VRY_PIN);
joystic->calibrate(ARDUINO_ADC_MIN, ARDUINO_ADC_MAX, AXES_DEVIATION);
```

How would I properly calibrate this @YuriiSalimov?

**Comment by thijstriemstra** [comment]
ah, because I'm using ESP32 the values are between 0 and 4095. So:

```cpp
#define ARDUINO_ADC_MIN 0
#define ARDUINO_ADC_MAX 4095
```

And because the joystick rotation is different I had to adjust accordingly:

```cpp
String moveTitle(const Joystick::Move move) {
  switch (move) {
    case Joystick::Move::NOT:
      return "CENTER";
    case Joystick::Move::PRESS:
      return "PRESS";
    case Joystick::Move::UP:
      return "RIGHT";
    case Joystick::Move::DOWN:
      return "LEFT";
    case Joystick::Move::RIGHT:
      return "UP";
    case Joystick::Move::LEFT:
      return "DOWN";
    default:
      return "???";
  }
}
```
